/* Minimal text extractor for the CEO Karnataka ASDDO booth PDFs.
   These are machine-generated by one ECI tool: no scanned images, base-14
   fonts, and every table cell is its own positioned `BT … x y Td (text) Tj ET`
   block. That makes a full PDF library unnecessary — and a dependency-free
   extractor is one less thing to break.

   Cells are matched to columns by x-coordinate rather than by counting tokens.
   Counting looks fine on a clean sample and then quietly corrupts every row
   that has a blank cell or a wrapped one: the offsets slide, and a relative's
   name ends up in the reason column. Geometry does not slide. */

import { inflateSync, unzipSync } from 'node:zlib';

/** Every drawn string with its page position, in drawing order. */
export function extractItems(buf) {
  const streams = [];
  const START = Buffer.from('stream');
  const END = Buffer.from('endstream');
  let from = 0;
  for (;;) {
    const s = buf.indexOf(START, from);
    if (s === -1) break;
    const e = buf.indexOf(END, s);
    if (e === -1) break;
    let a = s + START.length;
    if (buf[a] === 0x0d) a++;
    if (buf[a] === 0x0a) a++;
    let b = e;
    if (buf[b - 1] === 0x0a) b--;
    if (buf[b - 1] === 0x0d) b--;
    streams.push(buf.subarray(a, b));
    from = e + END.length;
  }

  const pages = [];
  for (const raw of streams) {
    let data = raw;
    // A zlib header's first byte is (window size << 4) | 8, so any of 0x08,
    // 0x18 … 0x78 is a valid deflate stream. Requiring 0x78 — the largest window
    // and the most common — silently skipped 1,006 of the 1,008 streams in
    // Siruguppa's list, which then read as a PDF containing no text at all, and
    // cost the site a whole constituency with no error anywhere.
    if ((raw[0] & 0x0f) === 8) {
      try {
        data = inflateSync(raw);
      } catch {
        try {
          data = unzipSync(raw);
        } catch {
          continue; // an image or a filter we don't handle
        }
      }
    }
    const items = parseContentStream(data.toString('latin1'));
    if (items.length) pages.push(items);
  }
  return pages;
}

// This generator emits trailing-dot numbers (`25.`, `0.`) as well as the usual
// forms, so the pattern has to accept an empty fractional part.
const NUM = '-?(?:\\d+\\.?\\d*|\\.\\d+)';
const OPS = new RegExp(
  [
    `(${NUM})\\s+(${NUM})\\s+Td`,                                    // 1,2   move
    `(${NUM})\\s+(${NUM})\\s+TD`,                                    // 3,4   move + set leading
    `(?:${NUM}\\s+){4}(${NUM})\\s+(${NUM})\\s+Tm`,                   // 5,6   absolute
    `(${NUM})\\s+TL`,                                                // 7     leading
    `\\(((?:[^()\\\\]|\\\\[\\s\\S])*)\\)\\s*Tj`,                     // 8     show
    `\\[((?:[^\\[\\]\\\\]|\\\\[\\s\\S])*)\\]\\s*TJ`,                 // 9     show array
    `(BT|ET|T\\*)`                                                   // 10    block / newline
  ].join('|'),
  'g'
);

function parseContentStream(text) {
  const items = [];
  let x = 0;
  let y = 0;
  let leading = 0;
  let m;
  OPS.lastIndex = 0;
  while ((m = OPS.exec(text)) !== null) {
    if (m[1] !== undefined) { x += +m[1]; y += +m[2]; }
    else if (m[3] !== undefined) { leading = -m[4]; x += +m[3]; y += +m[4]; }
    else if (m[5] !== undefined) { x = +m[5]; y = +m[6]; }
    else if (m[7] !== undefined) { leading = +m[7]; }
    else if (m[8] !== undefined) { push(unescapePdfString(m[8])); }
    else if (m[9] !== undefined) {
      // [(a) -250 (b)] TJ — concatenate the string parts, drop the kerning.
      const parts = [...m[9].matchAll(/\(((?:[^()\\]|\\[\s\S])*)\)/g)].map((p) => p[1]);
      push(unescapePdfString(parts.join('')));
    } else if (m[10] === 'BT') { x = 0; y = 0; }
    else if (m[10] === 'T*') { y -= leading; }
  }

  function push(str) {
    if (str) items.push({ x, y, text: str });
  }
  return items;
}

function unescapePdfString(s) {
  return s
    .replace(/\\([0-7]{1,3})/g, (_, o) => String.fromCharCode(parseInt(o, 8)))
    .replace(/\\n/g, ' ')
    .replace(/\\r/g, ' ')
    .replace(/\\t/g, ' ')
    .replace(/\\([()\\])/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
}

export const EPIC_RE = /^[A-Z]{3}[0-9]{7}$/;

/** True when the PDF is a scan we cannot read as text. */
export function looksScanned(buf) {
  const head = buf.toString('latin1');
  return /\/Subtype\s*\/Image/.test(head) && !/\)\s*Tj/.test(head);
}

// Districts print two widths of this table. The narrow one is the common case;
// the wide one adds Part No ahead of S.No. and Mapping/Category between the
// relative and the age. Columns the parser does not read still have to be
// anchored, or their values drift into the neighbour that is read — which is how
// Belgaum ended up with relatives named "LAKPMAN (Father) - KENCHAPPA".
const COLUMNS = [
  { key: 'partNo', header: 'Part No' },
  { key: 'sno', header: 'S.No.' },
  { key: 'serial', header: 'Serial No.' },
  { key: 'epic', header: 'EPIC Number' },
  { key: 'name', header: 'Elector Name' },
  { key: 'relative', header: 'Relative Details' },
  { key: 'mapping', header: 'Mapping' },
  { key: 'category', header: 'Category' },
  { key: 'dobAge', header: 'DOB/Age' },
  { key: 'reason', header: 'Uncollectable Reason' },
  // Uttara Kannada and others print a Photo Uploaded column (Yes/No) to the
  // right of the reason. Unmodelled, its value bled left into the reason —
  // "Death" became "Death -", and a blank reason became "- No" — which alone
  // put 76,933 non-deletion rows into Uttara Kannada's "others". Anchoring it
  // keeps its Yes/No out of the reason entirely.
  { key: 'photo', header: 'Photo Uploaded' }
];

// Without these the row is unreadable; the rest may or may not be printed.
const REQUIRED = ['sno', 'serial', 'epic', 'name', 'reason'];

/** Group items that share a baseline into one visual row, top of page first. */
function toRows(items, tolerance = 1.5) {
  const rows = [];
  for (const item of [...items].sort((a, b) => b.y - a.y || a.x - b.x)) {
    const last = rows[rows.length - 1];
    if (last && Math.abs(last.y - item.y) <= tolerance) last.cells.push(item);
    else rows.push({ y: item.y, cells: [item] });
  }
  for (const row of rows) row.cells.sort((a, b) => a.x - b.x);
  return rows;
}

/** Turn a booth PDF into rows. */
export function parseBoothPdf(buf) {
  const pages = extractItems(buf);
  const out = [];
  const meta = {};
  let unreadablePages = 0;

  // The AC/Part header prints when a booth's section begins and not again on
  // its continuation pages, so it has to carry forward. Scoped to the file:
  // a row belongs to the last section header seen above it.
  let pageAc = null;
  let pagePart = null;
  // Column anchors carry across pages within a file. A consolidated list runs a
  // booth's electors over several pages and repeats the column header only on
  // the first; the continuation pages have none. findHeader returns null there,
  // and every one of their rows was being dropped — 245 Siruguppa electors,
  // including whole booths, vanished this way. The x-layout is constant within a
  // file, so the last header's anchors apply.
  let lastAnchors = null;

  for (const items of pages) {
    const rows = toRows(items);

    // Every page carries the ECI's own identification of what is on it:
    //
    //   AC: 94-Bellary City; Part: 131-Sharada Vidya Peeta English Medium…
    //
    // Read per page, not once per file. A consolidated AC-wide list covers
    // hundreds of booths and changes Part as it goes, so taking only the first
    // line would stamp every row in the document with the first booth's number.
    // This is the only source of identity for districts whose file names carry
    // none — Bellary publishes four PDFs named 17858435222676.pdf and nothing
    // else, and 1,80,421 records sat under "AC ?" because of it.
    for (const row of rows) {
      const line = row.cells.map((c) => c.text).join(' ');
      if (/^AC:\s*/.test(line)) {
        if (!meta.acLine) meta.acLine = line;
        const m = /^AC:\s*(\d{1,3})\s*-\s*([^;]+?)\s*(?:;|$)/i.exec(line);
        if (m) pageAc = { no: +m[1], name: m[2].trim() };
        const p = /Part:\s*(\d{1,4})\s*-\s*(.+?)\s*$/i.exec(line);
        if (p) pagePart = { no: +p[1], name: p[2].trim() };
      }
      if (!meta.generatedOn) {
        const g = /Date of Generation:\s*([\d/]+)/.exec(line);
        if (g) meta.generatedOn = g[1];
      }
    }

    // Column x-positions come from this page's own header, because the
    // generator sizes columns to fit the widest value on the page. A page with
    // no header is a continuation: reuse the last page's anchors and treat every
    // row as data. Only a page that has no header and no predecessor is truly
    // unreadable.
    const header = findHeader(rows);
    let headerRow, anchors;
    if (header) {
      ({ headerRow, anchors } = header);
      lastAnchors = anchors;
    } else if (lastAnchors) {
      anchors = lastAnchors;
      headerRow = { y: Infinity };   // nothing to skip; the whole page is data
    } else {
      unreadablePages++;
      continue;
    }

    let current = null;
    const flush = () => {
      // Strip whitespace the EPIC never contains: in narrow tables the last
      // digit wraps to the next baseline (e.g. "STZ051150" + "1"), and the
      // continuation-merge below rejoins them with a space — "STZ051150 1".
      // Normalising here turns that back into a valid EPIC instead of dropping
      // the whole row (which silently lost every voter in Malleshwaram's
      // narrowest booths).
      if (current) current.epic = (current.epic ?? '').replace(/\s+/g, '');
      if (current && EPIC_RE.test(current.epic ?? '')) {
        const rec = finaliseRow(current);
        // A row whose Uncollectable Reason is blank ("-", or empty) is not a
        // deletion — the ASDDO list is exactly the electors who carry such a
        // reason. These appear in the wider files alongside real deletions and,
        // before this, were counted as "others". Drop them so the totals mean
        // what they say. hasReason keeps anything with a letter in it.
        if (hasReason(rec.reasonRaw)) out.push({ ...rec, pageAc, pagePart });
      }
      current = null;
    };

    for (const row of rows) {
      if (row.y >= headerRow.y) continue; // header and anything above it
      const cells = assign(row.cells, anchors);

      // Footer lines sit in the left-most column and are not numbered.
      const first = row.cells[0]?.text ?? '';
      if (/^(Date of Generation|Generated by|Note:|AC:|Page\b|View Enumeration)/i.test(first)) {
        flush();
        continue;
      }

      // Start a record on any numbered row whose EPIC is 3 letters + 6-or-7
      // digits: 7 is the clean case, 6 is a wrapped EPIC whose final digit sits
      // on the next baseline and gets appended by the continuation branch below.
      if (/^\d+$/.test(cells.sno ?? '') && /^[A-Z]{3}\d{6,7}$/.test((cells.epic ?? '').replace(/\s+/g, ''))) {
        flush();
        current = cells;
      } else if (current) {
        // A wrapped cell: same columns, next baseline, no new S.No.
        for (const key of Object.keys(cells)) {
          if (cells[key]) current[key] = `${current[key] ?? ''} ${cells[key]}`.trim();
        }
      }
    }
    flush();
  }

  // A file sometimes opens with data before its first section header, so the
  // earliest rows carry no constituency and land under "AC ?" — 4 of Siruguppa's
  // 32,153, enough to put a real elector in a bucket with no constituency name.
  // Back-fill from the first header the document does state; a booth list covers
  // one constituency, and a consolidated list names it before the rows that
  // matter.
  const firstAc = out.find((r) => r.pageAc)?.pageAc ?? null;
  const firstPart = out.find((r) => r.pagePart)?.pagePart ?? null;
  if (firstAc) for (const r of out) if (!r.pageAc) { r.pageAc = firstAc; r.pagePart ??= firstPart; }

  return { rows: out, meta, unreadablePages };
}

/**
 * Locate the column header and read the x-position of each column off it.
 *
 * A header label is not reliably one text object: some booths draw
 * "Serial No." as `Serial` + `No.`, and a narrow column can push a label onto
 * a second baseline. So instead of matching cell text exactly, walk the row
 * left to right accumulating cells until the buffer completes the next
 * expected label — the anchor is the x of the group's first cell.
 */
function findHeader(rows) {
  const norm = (s) => s.toLowerCase().replace(/[^a-z]/g, '');
  const labels = COLUMNS.map((c) => ({ ...c, want: norm(c.header) }));

  for (let i = 0; i < rows.length; i++) {
    // Allow the header to occupy up to three baselines. The narrowest booths
    // wrap a label over three lines ("Serial No." as "Seri" + "al" + "No."),
    // which a two-baseline span cannot complete. span=1 is tried first, so a
    // clean single-line header never pulls in the rows beneath it.
    for (const span of [1, 2, 3]) {
      const cells = rows
        .slice(i, i + span)
        .flatMap((r) => r.cells)
        .sort((a, b) => a.x - b.x);
      if (!cells.length) continue;

      // Match each label wherever it appears, rather than insisting the columns
      // arrive in one fixed order. A strict sequence cannot cope with a table
      // that has extra columns, and "Serial No." is drawn as "Serial" + "No." in
      // some booths, so a label may span several cells.
      const anchors = [];
      const taken = new Set();
      for (let c = 0; c < cells.length; c++) {
        // Skip cells that carry no letters (e.g. the lone "." left when "S.No."
        // is drawn as "S.No" + "."). If such a cell started a label buffer, the
        // anchor took ITS x — so "Serial No." anchored at the S.No column, its
        // values folded into sno as "1 1", and the whole booth parsed to nothing.
        if (taken.has(c) || !norm(cells[c].text)) continue;
        let buffer = '';
        for (let n = 0; n < 4 && c + n < cells.length; n++) {
          buffer += norm(cells[c + n].text);
          const hit = labels.find((l) => l.want === buffer && !anchors.some((a) => a.key === l.key));
          if (hit) {
            anchors.push({ key: hit.key, header: hit.header, x: cells[c].x });
            for (let k = 0; k <= n; k++) taken.add(c + k);
            c += n;
            break;
          }
          // Stop extending once no label could still start with this text.
          if (!labels.some((l) => l.want.startsWith(buffer))) break;
        }
      }

      anchors.sort((a, b) => a.x - b.x);
      const keys = new Set(anchors.map((a) => a.key));
      if (REQUIRED.every((k) => keys.has(k))) {
        return { headerRow: rows[i + span - 1], anchors };
      }
    }
  }
  return null;
}

function assign(cells, anchors) {
  const result = {};
  // Some districts print a wider table — "Part No" ahead of S.No., and Mapping
  // and Category between Relative Details and DOB/Age. The header matcher skips
  // the columns it does not model, but their *values* still arrive here, and a
  // Part No sitting left of the S.No. anchor was being folded into it: "1 1"
  // instead of "1", which fails the row test and yields a document with no rows.
  // 878 of Belgaum's 3,464 files parse to nothing for exactly this reason.
  // A cell left of the first anchor belongs to a column we do not read.
  const leftEdge = anchors[0].x - 2;
  for (const cell of cells) {
    if (cell.x < leftEdge) continue;
    let best = anchors[0];
    let bestDist = Infinity;
    for (const anchor of anchors) {
      // Cells are left-aligned in their column, so a cell belongs to the
      // nearest anchor at or to the left of it.
      const dist = cell.x >= anchor.x - 2 ? cell.x - anchor.x : (anchor.x - cell.x) * 4;
      if (dist < bestDist) {
        bestDist = dist;
        best = anchor;
      }
    }
    result[best.key] = result[best.key] ? `${result[best.key]} ${cell.text}` : cell.text;
  }
  return result;
}

// A real Uncollectable Reason contains letters ("Death", "Permanently Shifted").
// A blank one is empty, a dash, or the "Yes"/"No" left over from the Photo
// column before it was modelled — none of which marks a deletion.
const hasReason = (s) => /[a-z]/i.test((s ?? '').replace(/\b(yes|no)\b/gi, ''));

function finaliseRow(cells) {
  const relative = cells.relative ?? '';
  const dobAge = cells.dobAge ?? '';
  const reason = (cells.reason ?? '').replace(/\s+/g, ' ').trim();

  const relMatch = /\(([^)]+)\)\s*$/.exec(relative);
  const ageMatch = /\((\d{1,3})\)/.exec(dobAge);
  const dobMatch = /(\d{2}[/-]\d{2}[/-]\d{4})/.exec(dobAge);
  const dupMatch = /\(([A-Z]{3}\d{7})\)/.exec(reason);

  return {
    serial: /^\d+$/.test(cells.serial ?? '') ? +cells.serial : null,
    epic: cells.epic,
    name: (cells.name ?? '').replace(/\s+/g, ' ').trim(),
    relative: relative.replace(/\s*\([^)]*\)\s*$/, '').replace(/\s+/g, ' ').trim(),
    relation: relMatch ? relMatch[1].trim() : '',
    age: ageMatch ? +ageMatch[1] : null,
    dob: dobMatch ? dobMatch[1] : '',
    reasonRaw: reason,
    category: categorise(reason),
    dupEpic: dupMatch ? dupMatch[1] : ''
  };
}

/**
 * The PDFs never print the letters A/S/D/D/O — they print prose. This is the
 * mapping back onto the five official ASDDO buckets. Anything unrecognised
 * lands in `others` rather than being dropped, and 3-extract reports the
 * unmapped strings so new wording gets noticed instead of silently misfiled.
 */
export function categorise(reasonRaw) {
  const r = (reasonRaw || '').toLowerCase();
  if (!r) return 'others';
  if (/already enrolled|duplicate|repeat/.test(r)) return 'duplicate';
  if (/death|dead|expired|deceased/.test(r)) return 'death';
  // "Permanently" on its own shows up when the cell wraps awkwardly; the only
  // reason string in this dataset beginning that way is "Permanently Shifted".
  if (/shift|migrat|moved|permanent/.test(r)) return 'shifted';
  if (/absent|untrace|not found|non-?resident/.test(r)) return 'absent';
  return 'others';
}

export const CATEGORIES = ['absent', 'shifted', 'death', 'duplicate', 'others'];
